### ISSUE TITLE
Parking: TextEdit limitations

### ISSUE THREAD

**Issue by poolguy** [byu-oit-appdev/android-byu-suite-v2#150]
Name of Tester: Hammad
Feature: Parking

How to produce error:
Go to Parking. Add a vehicle. The model and the license should have a limit of how many characters can acutally be added to each field. Also We should limit the use of symbols in each of these feilds as atleast in license plate I dont think we need to use symbols. 

Expected Result:
Restrict Symbol Input and Restrict word limit of Fields

**Comment by romrell4** [comment]
The current length limit on iOS is 16 characters. We also currently disallow lower case characters and spaces. Please make sure that these limits exists on both text fields
