### ISSUE TITLE
Person Directory: Thin Spinner

### ISSUE THREAD

**Issue by poolguy** [byu-oit-appdev/android-byu-suite-v2#151]
Name of Tester: Hammad
Feature: Person Directory

How to produce error:
So when you come into Person Directory and click on the drop down filter options the spinner produced is way too thin. lets try to extend the width of this spinner till the end of the person Directory field. 

Expected Result:
Thicker Spinner

**Comment by romrell4** [comment]
Agree

**Comment by poolguy** [comment]
This doesn't appear to be possible for v21 devices
