### ISSUE TITLE
GPA Calculator: padding

### ISSUE THREAD

**Issue by poolguy** [byu-oit-appdev/android-byu-suite-v2#158]
Name of Tester: Seth
Feature: GPA Calculator

How to produce error:
I'm not certain if this is within our control at all but the padding on GPA calculator seems really bad

Expected Result:
There should be more padding on the sides of the text

![gpacalculatorpadding](https://cloud.githubusercontent.com/assets/17598928/22705726/ed45db56-ed29-11e6-91b5-86c3538780ff.png)

**Comment by coreywoodfield** [comment]
This is a webview, so the only option would be to add padding to the whole webview, which would look weird I think. @romrell4 do you agree?

**Comment by romrell4** [comment]
Yes
