### ISSUE TITLE
Department Directory: Loading (Pagination)

### ISSUE THREAD

**Issue by poolguy** [byu-oit-appdev/android-byu-suite-v2#160]
Name of Tester: Seth
Feature: Department Directory

How to produce error:
Loading seems to take a long time. We should consider using pagination here if possible.

Expected Result:
Less time with a progress dialog

**Comment by romrell4** [comment]
Sadly, this service does not allow for pagination. The one option we may have is to cache the data. However, I don't think that cacheing would be all that useful in this situation (because how many people really use this feature often enough to care?)

**Comment by poolguy** [comment]
Sounds good to me
