### ISSUE TITLE
Parking: "All fields must be selected" message

### ISSUE THREAD

**Issue by poolguy** [byu-oit-appdev/android-byu-suite-v2#163]
Name of Tester: Seth
Feature: Parking

How to produce error:
Add vehicle activity. Register button, without selecting all fields.

Expected Result:
Consider changing "Please select a valid value for the ___" to "All fields must be selected" or something like that

**Comment by romrell4** [comment]
There is one field that does not need to be selected. The nickname is optional. I think that telling the user which field is wrong is probably preferable

**Comment by poolguy** [comment]
Sounds good to me
