### ISSUE TITLE
Image quality

### ISSUE THREAD

**Issue by coreywoodfield** [byu-oit-appdev/android-byu-suite-v2#173]
The image quality in iOS is noticeably better than the image quality in android. I think we should up our compression quality in BitmapUtils.compressBitmapToByteArray, maybe even to 100 (0 is min quality, 100 is max - right now we're using 50)

**Comment by romrell4** [comment]
Please also look into the AED photos. I don't know if we pass them through a bundle, but one of the BETA testers commented that they were a little blurry
