### ISSUE TITLE
University Class Schedule: not very convenient formatting

### ISSUE THREAD

**Issue by coreywoodfield** [byu-oit-appdev/android-byu-suite-v2#176]
The section details is currently formatted as shown in the following example:
```
TTh 12:00p - 1:15p JFSB B137
Available Seats: 28/38
```
I think it'd be more clear if it was as follows:
```
TTh 12:00p - 1:15p
JFSB B137
Available Seats: 28/38
```
Also, this row is clickable in iOS and shows where the building is on a map. @romrell4 do we want to add this functionality to Android?

**Comment by romrell4** [comment]
I think that would be good functionality to have. Let's do it
