### ISSUE TITLE
Log In issues

### ISSUE THREAD

**Issue by poolguy** [byu-oit-appdev/android-byu-suite-v2#196]
Name of Tester: Seth
Feature: Favorites Activity

How to produce error:
Log in, log out, then attempt to log back in. A toast message pops up that says "Only on BYU account can be signed in at a time. To continue, you must remove the current account."

So it looks like maybe the log out functionality isn't working

![device-2017-02-16-103309](https://cloud.githubusercontent.com/assets/17598928/23034628/ac082ec0-f439-11e6-900d-d94c8d5d5d19.png)

**Comment by coreywoodfield** [comment]
It takes a few seconds after you hit the logout button before you actually get logged out. This only occurs if you try to log in immediately after logging out, which I think we do more than anyone else will.

**Comment by romrell4** [comment]
We also got one from a user saying this:
"Logged out. Got a never-ending loading symbol. I gave up waiting and click Log In"

**Comment by romrell4** [comment]
Also, there's an issue if you try to login with a bad credential. It just keeps spinning...

**Comment by coreywoodfield** [comment]
~If you left the LoginActivity by using the back button, it would trigger an error log, but there wasn't really an error so we should only trigger that if there's really an error~

FIXED BY #273
