### ISSUE TITLE
Department Directory: "Academic Class Scheduling" 

### ISSUE THREAD

**Issue by poolguy** [byu-oit-appdev/android-byu-suite-v2#207]
Tester: Seth

Problem:
The feature crashes when I click on the room number on the "Academic Class Scheduling" page. I was a using a Jelly Bean device when I was experiencing this error

This is the error:
"Unable to start activity ComponentInfo{edu.byu.suite/edu.byu.support.client.campusLocation.controller.BuildingActivity}: java.lang.ClassCastException: edu.byu.support.client.campusLocation.model.BuildingsWrapper$BuildingWrapper cannot be cast to edu.byu.support.client.campusLocation.model.Building"

**Comment by romrell4** [comment]
Duplicate of #237
