### ISSUE TITLE
Off Campus Housing: Filter Crash

### ISSUE THREAD

**Issue by poolguy** [byu-oit-appdev/android-byu-suite-v2#222]
Tester: Seth
Device: Jelly Bean device.

Problem:
On the filter activity, when I click "Reset" or "Done" the app always crashes. 
This is the error I get in LogCat:
"java.lang.NullPointerException: collection == null"

**Comment by romrell4** [comment]
I haven't been able to reproduce this. Can you try again? Maybe another fix solved it?

**Comment by poolguy** [comment]
I was only able to get this to happen on the Galaxy Note II, Android Version 4.3

**Comment by romrell4** [comment]
Is the feature using anything that would be needed from a certain SDK?
