### ISSUE TITLE
Off Campus Housing: Filter Activity - No up navigate button

### ISSUE THREAD

**Issue by poolguy** [byu-oit-appdev/android-byu-suite-v2#227]
Tester: Seth

Problem:
There is no up navigate button on OchFilterActivity

![device-2017-02-17-171948](https://cloud.githubusercontent.com/assets/17598928/23087936/4fa442de-f535-11e6-8993-119492a34e97.png)

**Comment by romrell4** [comment]
I think I'm okay with this one, as the Done button will do the same thing
