### ISSUE TITLE
Off Campus Housing: Apartment in the Atlantic Ocean

### ISSUE THREAD

**Issue by poolguy** [byu-oit-appdev/android-byu-suite-v2#236]
This isn't anything we did, but we should talk to whoever is in charge of the service. When you select graduate housing there appears to be a graduate apartment in the Atlantic Ocean off the coast of Western Africa

**Comment by romrell4** [comment]
We should clean out any annotations that are a ridiculous distance away. iOS only adds the annotation if it meets this criteria:

```
#define BYU_TOP_LEFT_LAT 40.255760
#define BYU_TOP_LEFT_LONG -111.656089
#define BYU_BOTTOM_RIGHT_LAT 40.244190
#define BYU_BOTTOM_RIGHT_LONG -111.643141
#define BUFFER 0.25

-(BOOL)isValidCoordinate:(CLLocationCoordinate2D)coordinate {
    float byuLatMax = BYU_TOP_LEFT_LAT + BUFFER;
    float byuLatMin = BYU_TOP_LEFT_LAT - BUFFER;
    float byuLongMax = BYU_TOP_LEFT_LONG + BUFFER;
    float byuLongMin = BYU_TOP_LEFT_LONG - BUFFER;
    
    return (coordinate.latitude <= byuLatMax && coordinate.latitude >= byuLatMin) && (coordinate.longitude <= byuLongMax && coordinate.longitude >= byuLongMin);
}
```

**Comment by coreywoodfield** [comment]
What about the Salt Lake Center? Is that included in these limits?

**Comment by romrell4** [comment]
Yes. It should include up to a little past Salt Lake. Test it though, just in case :)
