### ISSUE TITLE
Alumni Connect: Missing picture

### ISSUE THREAD

**Issue by poolguy** [byu-oit-appdev/android-byu-suite-v2#294]
There is a huge blank space in Alumni Connect where I assume a picture is supposed to go (as in IOS)

**Comment by coreywoodfield** [comment]
![device-2017-03-06-131551](https://cloud.githubusercontent.com/assets/17733030/23627705/1787190c-026f-11e7-8c43-127d8970f1a1.png)

This is what mine looks like... do you not see the image?

**Comment by romrell4** [comment]
I had a couple users from the studies report the same thing. Probably a device issue. Maybe v21 layout?
