### ISSUE TITLE
Person Directory lies

### ISSUE THREAD

**Issue by romrell4** [byu-oit-appdev/android-byu-suite-v2#295]
When I type in the characters "Ro", I get the "No results found." which isn't true

**Comment by coreywoodfield** [comment]
![screen shot 2017-03-06 at 4 02 10 pm](https://cloud.githubusercontent.com/assets/17733030/23634206/4b4bfd2c-0286-11e7-9717-93f922190adb.png)

It has the same functionality as the web interface. If they want a wildcard, they need to put it themselves

**Comment by coreywoodfield** [comment]
Conclusion: PersonDirectory doesn't lie. PersonDirectory on iOS lies.
