### ISSUE TITLE
Job Openings Crashing

### ISSUE THREAD

**Issue by romrell4** [byu-oit-appdev/android-byu-suite-v2#298]
I can't recreate the error, but about 1/3 of the users from the final BETA test said that the app was popping up the "server encountered an error" dialog... Test on as many devices as possible. Make sure the retry policy is working

**Comment by romrell4** [comment]
The bad Faculty listing has been fixed and doesn't throw errors. Still try testing on as many devices as possible to see if we can find why some people couldn't even load the feature

**Comment by poolguy** [comment]
@romrell4 Luke Rowley got back to me and it looks like he fixed the problem!
