### ISSUE TITLE
Parking: textView criteria

### ISSUE THREAD

**Issue by poolguy** [byu-oit-appdev/android-byu-suite-v2#350]
Issue: Model textview should not require the same logic as the license plate textview

**Comment by coreywoodfield** [comment]
Could you clarify a bit what needs to be done to close this issue? It's not at all clear what needs to be done

**Comment by romrell4** [comment]
I think it's that the textView for the "Model" field shouldn't have to be all upper case or be locked down to alpha numeric (should have spaces, special characters, etc)
