### ISSUE TITLE
Weird wrapping on galleries info

### ISSUE THREAD

**Issue by romrell4** [byu-oit-appdev/android-byu-suite-v2#359]
![image](https://cloud.githubusercontent.com/assets/15692420/24125968/fce07eea-0d90-11e7-84e4-aa61513d3b87.png)

**Comment by romrell4** [comment]
Also, let's italicize the secondary information (see iOS for details)

**Comment by coreywoodfield** [comment]
@romrell4 iOS doesn't italicize anything
